#Especifica que se usara el protocolo jdbc:postgresql, el setvidor esta en localhost (la misma mquina), el puerto es el 5432 (puerto estandar del postgresql) y la base de datos datos a la que se debe conectar es Red_Social.

spring.datasource.url=jdbc:postgresql://localhost:5432/red_social

#configura el nombre de usuario (postgres) que se utilizará para conectarse a la base de datos.

spring.datasource.username=postgres

#configura la clave asociada al usuario que se utilizará para conectarse a la base de datos.
#por si acaso cambiar la clave 1234 por la clave que le coloques de la base de datos
spring.datasource.password=1234

#establece el nombre de la aplicación Spring Boot como "seguridad"

spring.application.name=seguridad

#Especifica que se debe utilizar el controlador jdbc de postgresql para interactuar con una base de datos, informandp a spring como debe conectarse y debe comuiarse con una base de datos postgresql Especifica.

spring.datasource.driver-class-name=org.postgresql.Driver

#deshabilita la gestión automática del esquema de la base de datos por parte de Hibernate. Esto significa que Hibernate no realizará ninguna operación de lenguaje de definición de datos (DDL) como crear, actualizar o validar tablas al iniciar la aplicación; el esquema de la base de datos debe ser gestionado manualmente.

spring.jpa.hibernate.ddl-auto=none

#le dice a Spring y a Hibernate cómo generar el código SQL óptimo y las interacciones de persistencia específicas para la base de datos PostgreSQL, asegurando que el código de la aplicación pueda interactuar correctamente con ella sin necesidad de cambios.

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Consideraciones para producción:

#En un entorno de producción, las credenciales (host, usuario, contraseña) no deben estar codificadas directamente en application.properties.

#En su lugar, se deben utilizar variables de entorno o un sistema de geestión de secretos para cargar estas propiedades.

server.port=8081